services:
  omni-search:
    restart: unless-stopped
    build:
      context: .
      target: final
    expose:
      - 8080
    environment:
      CUBOX_TOKEN: ${CUBOX_TOKEN}
      TODOIST_TOKEN: ${TODOIST_TOKEN}
      NOTION_TOKEN: ${NOTION_TOKEN}
      BASE_STATIC_PATH: /static
      HTTP_PORT: 8080
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.omni-search.rule=Host(`omni-search.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.omni-search.entrypoints=https"
      - "traefik.http.routers.omni-search.tls.certresolver=le"

networks:
  proxy:
    external: true