name: Update Chrome Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release Chrome Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:extension

      - name: Package Extension
        run: |
          mkdir -p omni-turtle-search
          cp -r dist-extension/* omni-turtle-search/
          zip -r omni-turtle-search-extension-${{ github.ref_name }}.zip omni-turtle-search

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: omni-turtle-search-extension-${{ github.ref_name }}.zip
          draft: false
          generate_release_notes: true